### ISSUE TITLE
how to get c compile for unraid?

### ISSUE THREAD

**Issue by VergilGao** [ich777/alsa-custom#1]
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports nested variables... (cached) no
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/root/alsa/alsa-lib-1.2.4':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

**Comment by ich777** [comment]
Hi,
may I ask what you are doing with this? Did you know that there is a plugin already available, but not yet released:
`https://raw.githubusercontent.com/ich777/unraid-sound-driver/master/sound-driver.plg`

Anyways, where do you compile this? Keep in mind if you don't have the necessary dependencies installed it will not compile.

**Comment by VergilGao** [comment]
thank you! i dont know anything about this driver before.
i wanna make alsa for my sound card, i have installed gcc by the dev pack plugin.
im not good at english, so i cant describe my case accurately.
i tried this driver, and i can play sound on my usb sound card now, but my sound card on motherboard didn't.
```
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 10: HDMI 4 [HDMI 4]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by ich777** [comment]
Please send over your Diagnostics.

**Comment by VergilGao** [comment]
[xiaoyu-nas-diagnostics-20220304-1853.zip](https://github.com/ich777/alsa-custom/files/8185232/xiaoyu-nas-diagnostics-20220304-1853.zip)

sorry for the late reply

**Comment by ich777** [comment]
> sorry for the late reply

No worries, please give me a little time to look into this since it's weekend and that is usually dedicated to my little son.

**Comment by VergilGao** [comment]
I'm in no hurry, my usb sound card works well.
I hope you and your son had a nice weekend.

**Comment by ich777** [comment]
> I'm in no hurry, my usb sound card works well.

From what I see the Realtek sound card is detected properly and the Kernel Modules are also loaded:
```
00:1f.3 Audio device [0403]: Intel Corporation Device [8086:f0c8] (rev 11)
	DeviceName: Onboard - Sound
	Subsystem: Realtek Semiconductor Co., Ltd. Device [10ec:0662]
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel
```

Do you had speakers plugged in while you've installed the plugin?

What kind of USB sound card do you have? I don't see it in your system:
```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 1c4f:0002 SiGma Micro Keyboard TRACER Gamma Ivory
Bus 001 Device 004: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 001 Device 003: ID 0781:5571 SanDisk Corp. Cruzer Fit
Bus 001 Device 002: ID 0463:ffff MGE UPS Systems UPS
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by VergilGao** [comment]
this is my lsusb output.
```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 1c4f:0002 SiGma Micro Keyboard TRACER Gamma Ivory
Bus 001 Device 004: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 001 Device 006: ID 1b3f:2008 Generalplus Technology Inc. USB Audio Device
Bus 001 Device 003: ID 0781:5571 SanDisk Corp. Cruzer Fit
Bus 001 Device 002: ID 0463:ffff MGE UPS Systems UPS
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
sorry, i forgot to plugin my soud card before.

i plug a speaker now, how to test my Realtek sound card? i cant find it in my aplay -l output:
```
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 10: HDMI 4 [HDMI 4]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by ich777** [comment]
> i plug a speaker now, how to test my Realtek sound card?

Please try to reboot the server with speakers plugged in maybe that is the issue here, if not I have to test this myself on my server.

**Comment by VergilGao** [comment]
i tried to reboot and it didnt work.

**Comment by ich777** [comment]
> i tried to reboot and it didnt work.

I will look into this on my server if it's the same, give me a few days, I'm planing releasing the plugin in the near future and need to do some more testing anyways, I will keep you updated!

**Comment by VergilGao** [comment]
hello, i found i got a new version in my unraid 6.9.2 server, but this issue still not fix.
i found my on board sound card is ALC897. 
my `lspci -vv | grep -i audio` output is :
```
00:1f.3 Audio device: Intel Corporation Device f0c8 (rev 11)
```
It looks like the audio output of the Intel Core Graphics. So I don't think the card was successfully driven.

**Comment by ich777** [comment]
Yes I know, because currently I have no time to look into this, develop the plugin any further and as said this plugin is not ready for production use yet.

**Comment by VergilGao** [comment]
> Yes I know, because currently I have no time to look into this, develop the plugin any further and as said this plugin is not ready for production use yet.

So, is there anything I can do to help?

**Comment by VergilGao** [comment]
I think I found the direction, it is said that unraid is a Linux distribution based on Slackware, I found the compiler script of Bluez-alsa in [Slackbuilds repo](https://slackbuilds.org/repository/15.0/libraries/bluez-alsa/)

**Comment by ich777** [comment]
Exactly, you can put every Slackware package in /boot/packages and it will be automatically installed on boot.
Keep in mind at time of writing Unraid is based on Slackware 15 so make sure you download packages for Slackware 15.

**Comment by VergilGao** [comment]
> Exactly, you can put every Slackware package in /boot/packages and it will be automatically installed on boot. Keep in mind at time of writing Unraid is based on Slackware 15 so make sure you download packages for Slackware 15.

My plan is to build a Slackware 15 virtual machine dedicated to compiling plugins

**Comment by ich777** [comment]
> Slackware 15

Why? You can also cross compile on for example Debian, I for example compile everything in a Docker container directly on Unraid an have no issue whatsoever.

**Comment by VergilGao** [comment]
> > Slackware 15
> 
> Why? You can also cross compile on for example Debian, I for example compile everything in a Docker container directly on Unraid an have no issue whatsoever.

Thanks for the reminder, I think I can do my plan on the ubuntu virtual machine which I use for development.
I don't really want to compile directly in my unraid host.

**Comment by ich777** [comment]
That‘s why I also compile not directly on Unraid itself and my test machine isn‘t simply powerful enough.

**Comment by VergilGao** [comment]
I successfully connected to my bluetooth speaker with bluealsa and played the sound, but unfortunately the process is too complicated to explain to the average user.
Meanwhile, my ultimate goal is to let owntone-server use bluetooth speaker with bluealsa, I found a way https://github.com/Arkq/bluez-alsa/wiki/Using-BlueALSA-with-dmix ready to try again when I have time .
